[build]
  base = "/"
  publish = "dist/apps/web/browser"
  command = "npm install && npx nx build web --configuration=production && npx nx build server --configuration=production"
  functions = ".netlify/functions-serve"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/server/"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  framework = "#custom"
  targetPort = 4200
  port = 8888
  autoLaunch = false
  timeout = 120
