[build]
  base = "/"
  publish = "dist/apps/web/browser"
  command = "npm install && npx nx build web --configuration=production && npx nx build server --configuration=production"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npx nx serve web"
  targetPort = 4200
  port = 8888
  publish = "dist/apps/web/browser"
  autoLaunch = false
